### ISSUE TITLE
Correctly handle OsString

### ISSUE THREAD

**Issue by Qwaz** [PLUS-POSTECH/soma#44]
Currently, Soma mixes OsString and String in its internal code.
This prevents using non-unicode file name even though host OS supports it.

Edit: non-UTF-8 to non-unicode

**Comment by KSAlpha** [comment]
Soma implementations rejects non-unicode file name only when building docker images.

As non-unicode filename is a very rare use case, I would like to mark this as `wontfix`. Also, it seems to be a very hard problem to fix.

Supporting non-unicode filename is hard to address because:

- Soma supports both Windows and Linux systems.
  (i.e. unix OsStr is not reachable from Windows host)
- Text encoding of `soma.toml` may occur non-unicode texts to be lost.

But, we would like to provide some workarounds later by supporting user-defined script, which will executed inside the container in build time. And, by renaming some files using the script, non-unicode filenames can be present inside the image.
